 export const mockManagers = [
    { id: "1", name: "Rahul Kumar" },
    { id: "2", name: "Priya Singh" },
    { id: "3", name: "Amit Sharma" },
    { id: "4", name: "Neha Verma" },
    { id: "5", name: "Ankit Mehra" },
    { id: "6", name: "Sneha Rathi" },
    { id: "7", name: "Vikram Joshi" },
    { id: "8", name: "Kiran Patel" },
    { id: "9", name: "Harshit Jain" },
    { id: "10", name: "Deepika Das" },
    { id: "11", name: "Ravi Yadav" },
    { id: "12", name: "Megha Kapoor" },
    { id: "13", name: "Sumit Bansal" },
    { id: "14", name: "Pooja Bhatt" },
    { id: "15", name: "Nitesh Agarwal" },
    { id: "16", name: "Komal Chauhan" },
    { id: "17", name: "Sandeep Sinha" },
    { id: "18", name: "Tanya Malhotra" },
    { id: "19", name: "Ajay Dev" },
    { id: "20", name: "Ruchi Nair" },
    { id: "21", name: "Aditya Rao" },
    { id: "22", name: "Ritika Sehgal" },
    { id: "23", name: "Mohit Singh" },
    { id: "24", name: "Nidhi Goyal" },
    { id: "25", name: "Kunal Chopra" },
  ];

   export const mockEmployees = [
    { id: "1", name: "Rahul Kumar" },
    { id: "2", name: "Priya Singh" },
    { id: "3", name: "Amit Sharma" },
    { id: "4", name: "Neha Verma" },
    { id: "5", name: "Ankit Mehra" },
    { id: "6", name: "Sneha Rathi" },
    { id: "7", name: "Vikram Joshi" },
    { id: "8", name: "Kiran Patel" },
    { id: "9", name: "Harshit Jain" },
    { id: "10", name: "Deepika Das" },
    { id: "11", name: "Ravi Yadav" },
    { id: "12", name: "Megha Kapoor" },
    { id: "13", name: "Sumit Bansal" },
    { id: "14", name: "Pooja Bhatt" },
    { id: "15", name: "Nitesh Agarwal" },
    { id: "16", name: "Komal Chauhan" },
    { id: "17", name: "Sandeep Sinha" },
    { id: "18", name: "Tanya Malhotra" },
    { id: "19", name: "Ajay Dev" },
    { id: "20", name: "Ruchi Nair" },
    { id: "21", name: "Aditya Rao" },
    { id: "22", name: "Ritika Sehgal" },
    { id: "23", name: "Mohit Singh" },
    { id: "24", name: "Nidhi Goyal" },
    { id: "25", name: "Kunal Chopra" },
  ];

  export const mockProjects = [
  {
    id: '1',
    title: 'Design a new website',
    description: 'Create a modern, responsive website for the company.',
    taskCount: 12,
    startDate: '2025-07-01',
    endDate: '2025-08-15',
    manager: 'Priya Singh', 
    employees: ['Rahul Kumar', 'Priya Singh', 'Ankit Mehra'], 
  },
  {
    id: '2',
    title: 'Plan a marketing campaign',
    description: 'asdfghjklkjhgfdsa',
    taskCount: 8,
    startDate: '',
    endDate: '',
    manager: '', 
    employees: [], 
  },
  {
    id: '3',
    title: 'Develop a mobile app',
    description: 'Build an iOS and Android app for our core services.',
    taskCount: 15,
    startDate: '2025-07-05',
    endDate: '2025-09-01',
    manager: 'Sneha Rathi',
    employees: ['Megha Kapoor', 'Ritika Sehgal', 'Aditya Rao'], 
  },
  {
    id: '4',
    title: 'Organize a team retreat',
    description: 'Plan and organize an offsite team-building retreat.',
    taskCount: 5,
    startDate: '2025-08-01',
    endDate: '2025-08-05',
    manager: 'Mohit Singh', 
    employees: ['Komal Chauhan', 'Sandeep Sinha'], 
  },
];

export const mockTasks = [
  {
    id:"1",
    title: "Design Login Page",
    description: "Create UI design for login screen",
    startDate: "2025-07-01",
    endDate: "2025-07-03",
    status: "todo",
    assignee: "Alice Johnson",
    priority: "High",
  },
  {
    id:"2",
    title: "Setup Backend Server",
    description: "Initialize Express.js server and basic routes",
    startDate: "2025-07-04",
    endDate: "2025-07-06",
    assignee: "Bob Smith",
    status: "todo",
    priority: "Medium",
  },
  {
    id:"3",
    title: "Implement Authentication",
    description: "Add JWT-based login and signup APIs",
    startDate: "2025-07-07",
    endDate: "2025-07-09",
    status: "todo",
    assignee: "Charlie Davis",
    priority: "High",
  },
  {
    id:"4",
    title: "Connect Frontend with API",
    description: "Use Axios to fetch data from backend in React Native",
    startDate: "2025-07-10",
    endDate: "2025-07-12",
    status: "todo",
    assignee: "Diana Lee",
    priority: "Low",
  },
  {
    id:"5",
    title: "Testing & Debugging",
    description: "Write test cases and fix identified issues",
    startDate: "2025-07-13",
    endDate: "2025-07-15",
    assignee: "Ethan Brown",
    status: "todo",
    priority: "Medium",
  },
];
